name: CI/CD Emploi-Retour

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:
    branches: [main]

jobs:
  test: # Vérifie qu'il n'y a pas de régressions dans le code via les tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          pip install -r services/model/requirements.txt pytest httpx
          pip install -r services/backend/requirements.txt pytest httpx
      - name: Tests unitaires model + contract test du modèle
        run: |
          pytest -v services/model/tests
      - name: Tests unitaires backend
        run: |
          pytest -v services/backend/tests
      - name: Tests unitaires frontend
        run: |
          pytest -v services/frontend/tests

  build-and-push:
    needs: test
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    permissions: { contents: read, packages: write }
    strategy:
      max-parallel: 1 # Un seul push à la fois
      matrix:
        service: [model, backend, frontend]
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          IMG="ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')-${{ matrix.service }}"
          TAG="${GITHUB_REF_NAME//\//-}"
          docker build -t "$IMG:$TAG" ./services/${{ matrix.service }}
          docker push "$IMG:$TAG"
